services:
  prometheus:
    image: prom/prometheus:v3.15.0
    container_name: lab-prom-grafana-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  alertmanager:
    image: prom/alertmanager:v0.34.1
    container_name: lab-prom-grafana-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
networks:
  default:
    name: lab
